version: '3'

services:
  traefik:
    image: traefik:v2.2
    container_name: traefik
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - AWS_HOSTED_ZONE_ID
    command: 
      - "--api.insecure=true"
      - "--log.level=debug"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls.domains[0].main=internal.murawsky.net"
      - "--entrypoints.websecure.http.tls.domains[0].sans=*.internal.murawsky.net"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=route53"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.email=dmurawsky@gmail.com"  
    ports:
      - "80:80"
      - "443:443"
    expose:
      - 8080
    volumes:
      - "./letsencrypt:/letsencrypt"
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`iss.internal.murawsky.net`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik.service=api@internal"
    
    restart: "always"

    networks:
      - web

  whoami:
    image: "containous/whoami"
    container_name: "whoami"
    expose:
    - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.internal.murawsky.net`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=letsencrypt"
      - "traefik.port=80"
    networks:
      - web

networks:
  web:
    external: true